include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

.vars-devel:
  variables:
    MANIFEST_PATH: "flatpak/info.febvre.Komikku.Devel.json"
    FLATPAK_MODULE: "komikku"
    APP_ID: "info.febvre.Komikku.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "info.febvre.Komikku.Devel.flatpak"

flake8:
  image: python:3.10
  script:
    - pip install flake8
    - flake8 komikku

# Build Flatpak for x86_64
flatpak@x86_64:
  extends: ['.flatpak@x86_64', '.vars-devel']

# Build Flatpak for aarch64
flatpak@aarch64:
  extends: ['.flatpak@aarch64', '.vars-devel']
