include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  APP_ID: "info.febvre.Komikku.Devel"
  BUNDLE: "info.febvre.Komikku.Devel.flatpak"
  FLATPAK_MODULE: "komikku"
  MANIFEST_PATH: "flatpak/info.febvre.Komikku.Devel.json"
  RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"

flake8:
  image: python:3.10
  script:
    - pip install flake8
    - flake8 komikku

flatpak:
  stage: 'test'
  extends: '.flatpak@x86_64'
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:x86_64-gnome-44'

flatpak@aarch64:
  stage: 'test'
  extends: '.flatpak@aarch64'
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:aarch64-gnome-44'
