repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    # Identify invalid files
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml

    # git checks
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-case-conflict

    # Python checks
    -   id: check-docstring-first
    -   id: requirements-txt-fixer
    -   id: fix-byte-order-marker

    # General quality checks
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: check-executables-have-shebangs
    -   id: end-of-file-fixer
        exclude: ^.*\.json$

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
